
FROM python:3.11.8

# Créer le dossier de l'application
RUN mkdir -p /app/data/raw /app/repo

# Copier tous les fichiers nécessaires
COPY . /app

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
RUN apt update && apt install -y git && pip install dvc
RUN pip install --no-cache-dir -r requirements.txt

# Lancer le script d'ingestion
CMD ["sh", "-c", "python script_meteo.py && python dvc_push.py --folder /app/repo"]
