
FROM python:3.9-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/config    

WORKDIR /app

COPY * /app/src/preprocess/
COPY  * /app/config/config.yaml

# COPY ./data/raw/weatherAUS.csv /app/data/raw/weatherAUS.csv
# COPY ./dvc.yaml /app/dvc.yaml

RUN pip install --no-cache-dir -r /app/src/preprocess/requirements.txt dvc
RUN dvc init --no-scm && \
    dvc remote add origin https://dagshub.com/bmle-aug24/Meteo_group.dvc && \
    dvc remote modify origin auth basic && \
    dvc remote modify origin user bmle-aug24 && \
    dvc remote modify origin password 80f0fd7d1ab6a2b1e95664936d78045d71c78e17 && \
    dvc pull # Récupère les fichiers versionnés depuis DagsHub

# Ajouter une commande shell pour gérer le traitement des données et le versionnement
CMD ["sh", "-c", "python /app/src/preprocess/preprocess.py && \
    dvc add /app/data/processed/X_train.csv && \
    dvc add /app/data/processed/X_test.csv && \
    dvc add /app/data/processed/y_train.csv && \
    dvc add /app/data/processed/y_test.csv && \
    dvc push"]